#! /bin/sh
#
# run-polaris
# Copyright (C) 2018-2025 Óscar García Amor <ogarcia@connectical.com>
#
# Distributed under terms of the GNU GPLv3 license.
#

POLARIS_ARGS="-p ${POLARIS_PORT:-5050}"
[ -n "${POLARIS_CONFIG}" ] && POLARIS_ARGS="${POLARIS_ARGS} -c ${POLARIS_CONFIG}"
[ -n "${POLARIS_DB}" ] && POLARIS_ARGS="${POLARIS_ARGS} -d ${POLARIS_DB}"
[ -n "${POLARIS_CACHE_DIR}" ] && POLARIS_ARGS="${POLARIS_ARGS} --cache ${POLARIS_CACHE_DIR}"
[ -n "${POLARIS_PIDFILE}" ] && POLARIS_ARGS="${POLARIS_ARGS} --pid ${POLARIS_PIDFILE}"
[ -n "${POLARIS_LOGFILE}" ] && POLARIS_ARGS="${POLARIS_ARGS} --log ${POLARIS_LOGFILE}"
[ -n "${POLARIS_LOGLEVEL}" ] && POLARIS_ARGS="${POLARIS_ARGS} --log-level ${POLARIS_LOGLEVEL}"
${POLARIS_DAEMONIZE:-false} || POLARIS_ARGS="${POLARIS_ARGS} -f"

polaris ${POLARIS_ARGS}
